USE Bibliothek;
CREATE TABLE Autoren (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 Nachname VARCHAR(50) NOT NULL,
 Vorname VARCHAR(50) NOT NULL,
 Adresse VARCHAR(20),
 OrtID INT
);
CREATE TABLE Verlage (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 Verlag VARCHAR(50) NOT NULL,
 Email VARCHAR(100),
 Telefonnr VARCHAR(20)
);
CREATE TABLE Autoren_Verlage (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 AutorID INT NOT NULL,
 VerlagID INT NOT NULL
);
CREATE TABLE Genres (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 Genre VARCHAR(50) NOT NULL,
 Fiktion BOOLEAN NOT NULL
);
CREATE TABLE Autoren_Genres (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 AutorID INT NOT NULL,
 GenreID INT NOT NULL
);
CREATE TABLE Buecher (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 ISBN CHAR(17),
 Titel VARCHAR(50) NOT NULL,
 Erscheinungsdatum DATE,
 Anzahl INT NOT NULL,
 AutorID INT NOT NULL,
 VerlagID INT NOT NULL,
 GenreID INT
);
CREATE TABLE Orte (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 PLZ INT NOT NULL,
 Ort VARCHAR(50) NOT NULL
);
CREATE TABLE Kunden (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 Nachname VARCHAR(50) NOT NULL,
 Vorname VARCHAR(50) NOT NULL,
 Adresse VARCHAR(100),
 Email VARCHAR(100),
 Geburtsdatum DATE,
 OrtID INT NOT NULL
);
CREATE TABLE Ausleihen (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 Datum_von DATETIME NOT NULL,
 Datum_bis DATETIME NOT NULL,
 Preis FLOAT,
 KundeID INT NOT NULL,
 BuchID INT NOT NULL
);
